name: Job Monitor Schedule

on:
  schedule:
    # Раз в час
    - cron: '0 * * * *'
    # Каждый день в 9:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # позволяет запускать вручную из интерфейса GitHub

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hourly scan
        if: github.event.schedule == '0 * * * *'
        run: python3 main.py --scan

      - name: Run daily report
        if: github.event.schedule == '0 9 * * *'
        run: python3 main.py --report
